apiVersion: v1
kind: Namespace
metadata:
  name: ihelp
---
apiVersion: v1
kind: Service
metadata:
    name: ihelp-router
    namespace: ihelp
spec:
    type: LoadBalancer
    selector:
        app: router
    ports:
    - name: "main"
      port: 30000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: ihelp-pgadmin
    namespace: ihelp
spec:
    type: LoadBalancer
    selector:
        app: pgadmin
    ports:
    - name: "pgadmin"
      port: 30001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-db
  namespace: ihelp
spec:
  ports:
  - name: db-port
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-client
  namespace: ihelp
spec:
  ports:
  - name: client-port
    protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: client
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-server
  namespace: ihelp
spec:
  ports:
  - name: server-port
    protocol: "TCP"
    port: 3001
    targetPort: 3001
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-router
  namespace: ihelp
spec:
  replicas: 1
  selector:
      matchLabels:
        app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: router-config
        - mountPath: /etc/nginx/.htpasswd
          name: router-passwd
      volumes:
      - name: router-config
        hostPath:
          path: /core/ihelp/ihelp-app/nginx/nginx.conf
          type: File
      - name: router-passwd
        hostPath:
          path: /core/ihelp/ihelp-app/nginx/.htpasswd
          type: File
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-client
  namespace: ihelp
spec:
  replicas: 1
  selector:
      matchLabels:
        app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: node:12
        ports:
        - containerPort: 3000
        command: ["npm"]
        args: ["run", "dev"]
        env:
        - name: PORT
          value: "3000"
        workingDir: /core
        volumeMounts:
        - mountPath: /core
          name: client-volume
      volumes:
      - name: client-volume
        hostPath:
          path: /core/ihelp/ihelp-app/client
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-server
  namespace: ihelp
spec:
  replicas: 1
  selector:
      matchLabels:
        app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: node:12
        ports:
        - containerPort: 3001
        command: ["npm"]
        args: ["run", "server"]
        env:
        - name: PORT
          value: "3001"
        workingDir: /core
        volumeMounts:
        - mountPath: /core
          name: server-volume
      volumes:
      - name: server-volume
        hostPath:
          path: /core/ihelp/ihelp-app
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-db
  namespace: ihelp
spec:
  replicas: 1
  selector:
      matchLabels:
        app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:12
        env:
        - name: POSTGRES_DB
          value: "ihelp"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "gisp123"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/10/main
          name: db-main-volume
        - mountPath: /var/lib/postgresql/data
          name: db-data-volume
      volumes:
      - name: db-main-volume
        hostPath:
          path: /core/ihelp/ihelp-app/modules/postgresql/main
          type: Directory
      - name: db-data-volume
        hostPath:
          path: /core/ihelp/ihelp-app/modules/postgresql/data
          type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-pgadmin
  namespace: ihelp
spec:
  replicas: 1
  selector:
      matchLabels:
        app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: biarms/pgadmin4
        name: pgadmin
        env:
        - name: PG_ADMIN_PORT
          value: "8001"
        volumeMounts:
        - mountPath: /pgadmin
          name: pgadmin-vol
        - mountPath: /usr/local/lib/python2.7/site-packages/flask_babelex/__init__.py
          name: pgadmin-init
      volumes:
      - name: pgadmin-init
        hostPath:
          path: /core/ihelp/ihelp-app/modules/postgresql/pgadmin/__init__.py
          type: File
      - name: pgadmin-vol
        hostPath:
          path: /core/ihelp/ihelp-app/modules/postgresql/pgadmin
          type: Directory
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihelp-collect
  namespace: ihelp
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: collect
        spec:
          restartPolicy: OnFailure
          containers:
          - name: collect
            image: node:12
            volumeMounts:
            - mountPath: /core/ihelp
              name: ihelp-volume
            workingDir: /core/ihelp/ihelp-dev/packages/hardhat/scripts
            command: ["./runCollect.sh"]
          volumes:
          - name: ihelp-volume
            hostPath:
              path: /core/ihelp
              type: Directory
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihelp-upkeep
  namespace: ihelp
spec:
  schedule: "0 */12 * * *" # every 12 hours
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: upkeep
        spec:
          restartPolicy: OnFailure
          containers:
          - name: upkeep
            image: node:12
            volumeMounts:
            - mountPath: /core/ihelp
              name: ihelp-volume
            workingDir: /core/ihelp/ihelp-dev/packages/hardhat/scripts
            command: ["./runUpkeep.sh"]
          volumes:
          - name: ihelp-volume
            hostPath:
              path: /core/ihelp
              type: Directory
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihelp-reward
  namespace: ihelp
spec:
  schedule: "0 0 */3 * *" # every 3 days
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            app: reward
        spec:
          restartPolicy: OnFailure
          containers:
          - name: reward
            image: node:12
            volumeMounts:
            - mountPath: /core/ihelp
              name: ihelp-volume
            workingDir: /core/ihelp/ihelp-dev/packages/hardhat/scripts
            command: ["./runReward.sh"]
          volumes:
          - name: ihelp-volume
            hostPath:
              path: /core/ihelp
              type: Directory
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ihelp-collect
#   namespace: ihelp
# spec:
#   replicas: 1
#   selector:
#       matchLabels:
#         app: collect
#   template:
#     metadata:
#       labels:
#         app: collect
#     spec:
#       containers:
#       - name: collect
#         image: node:12
#         volumeMounts:
#         - mountPath: /core/ihelp
#           name: ihelp-volume
#         workingDir: /core/ihelp/ihelp-dev/packages/hardhat/scripts
#         command: ["./runCollect.sh"]
#       volumes:
#       - name: ihelp-volume
#         hostPath:
#           path: /core/ihelp
#           type: Directory

# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ihelp
