apiVersion: v1
kind: Service
metadata:
    name: ihelp-router
    namespace: ihelp-app-avax
spec:
    type: LoadBalancer
    selector:
        app: router
    ports:
    - name: "main"
      nodePort: 30011
      port: 30011
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: ihelp-pgadmin
    namespace: ihelp-app-avax
spec:
    type: LoadBalancer
    selector:
        app: pgadmin
    ports:
    - name: "pgadmin"
      nodePort: 30012
      port: 30012
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-db
  namespace: ihelp-app-avax
spec:
  ports:
  - name: db-port
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: db
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-client
  namespace: ihelp-app-avax
spec:
  ports:
  - name: client-port
    protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: client
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-client-dev
  namespace: ihelp-app-avax
spec:
  type: LoadBalancer
  ports:
  - name: client-dev-port
    nodePort: 30013
    port: 30013
    targetPort: 3003
  selector:
    app: client-dev
---
apiVersion: v1
kind: Service
metadata:
  name: ihelp-server
  namespace: ihelp-app-avax
spec:
  ports:
  - name: server-port
    protocol: "TCP"
    port: 3001
    targetPort: 3001
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-router
  namespace: ihelp-app-avax
spec:
  replicas: 1
  selector:
      matchLabels:
        app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: ihelp-app-avax/nginx/nginx.conf
          name: ihelp-files
        - mountPath: /etc/nginx/.htpasswd
          subPath: ihelp-app-avax/nginx/.htpasswd
          name: ihelp-files
      volumes:
      - name: ihelp-files
        persistentVolumeClaim:
          claimName: ihelp-app-avax-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-client
  namespace: ihelp-app-avax
spec:
  replicas: 1
  selector:
      matchLabels:
        app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: node:12
        ports:
        - containerPort: 3000
        command: ["npm"]
        args: ["start"]
        env:
        - name: PORT
          value: "3000"
        workingDir: /core
        volumeMounts:
        - mountPath: /core
          subPath: ihelp-app-avax/client
          name: ihelp-files
      volumes:
      - name: ihelp-files
        persistentVolumeClaim:
          claimName: ihelp-app-avax-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-client-dev
  namespace: ihelp-app-avax
spec:
  replicas: 1
  selector:
      matchLabels:
        app: client-dev
  template:
    metadata:
      labels:
        app: client-dev
    spec:
      containers:
      - name: client-dev
        image: node:12
        ports:
        - containerPort: 3003
        command: ["npm"]
        args: ["start"]
        env:
        - name: PORT
          value: "3003"
        workingDir: /core/packages/react-app
        volumeMounts:
        - mountPath: /core
          subPath: ihelp-dev-avax
          name: ihelp-files
      volumes:
      - name: ihelp-files
        persistentVolumeClaim:
          claimName: ihelp-app-avax-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-server
  namespace: ihelp-app-avax
spec:
  replicas: 1
  selector:
      matchLabels:
        app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: node:12
        ports:
        - containerPort: 3001
        command: ["npm"]
        args: ["run", "server"]
        env:
        - name: PORT
          value: "3001"
        workingDir: /core
        volumeMounts:
        - mountPath: /core
          subPath: ihelp-app-avax
          name: ihelp-files
      volumes:
      - name: ihelp-files
        persistentVolumeClaim:
          claimName: ihelp-app-avax-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-db
  namespace: ihelp-app-avax
spec:
  replicas: 1
  selector:
      matchLabels:
        app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:12
        env:
        - name: POSTGRES_DB
          value: "ihelp"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "gisp123"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/10/main
          subPath: ihelp-app-avax/modules/postgresql/main
          name: ihelp-files
        - mountPath: /var/lib/postgresql/data
          subPath: ihelp-app-avax/modules/postgresql/data
          name: ihelp-files
      volumes:
      - name: ihelp-files
        persistentVolumeClaim:
          claimName: ihelp-app-avax-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihelp-pgadmin
  namespace: ihelp-app-avax
spec:
  replicas: 1
  selector:
      matchLabels:
        app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - image: biarms/pgadmin4
        name: pgadmin
        env:
        - name: PG_ADMIN_PORT
          value: "8001"
        volumeMounts:
        - mountPath: /pgadmin
          subPath: ihelp-app-avax/modules/postgresql/pgadmin
          name: ihelp-files
        - mountPath: /usr/local/lib/python2.7/site-packages/flask_babelex/__init__.py
          subPath: ihelp-app-avax/modules/postgresql/pgadmin/__init__.py
          name: ihelp-files
      volumes:
      - name: ihelp-files
        persistentVolumeClaim:
          claimName: ihelp-app-avax-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihelp-collect
  namespace: ihelp-app-avax
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: collect
        spec:
          restartPolicy: OnFailure
          containers:
          - name: collect
            image: node:12
            volumeMounts:
            - mountPath: /core/ihelp
              name: ihelp-files
            workingDir: /core/ihelp/ihelp-dev-avax/packages/hardhat/scripts
            command: ["./runCollect.sh"]
          volumes:
          - name: ihelp-files
            persistentVolumeClaim:
              claimName: ihelp-app-avax-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihelp-upkeep
  namespace: ihelp-app-avax
spec:
  schedule: "0 0 */3 * *" # every 3 days
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: upkeep
        spec:
          restartPolicy: OnFailure
          containers:
          - name: upkeep
            image: node:12
            volumeMounts:
            - mountPath: /core/ihelp
              name: ihelp-files
            workingDir: /core/ihelp/ihelp-dev-avax/packages/hardhat/scripts
            command: ["./runUpkeep.sh"]
          volumes:
          - name: ihelp-files
            persistentVolumeClaim:
              claimName: ihelp-app-avax-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ihelp-reward
  namespace: ihelp-app-avax
spec:
  schedule: "0 1 */3 * *" # every 3 days
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 120
      template:
        metadata:
          labels:
            app: reward
        spec:
          restartPolicy: OnFailure
          containers:
          - name: reward
            image: node:12
            volumeMounts:
            - mountPath: /core/ihelp
              name: ihelp-files
            workingDir: /core/ihelp/ihelp-dev-avax/packages/hardhat/scripts
            command: ["./runReward.sh"]
          volumes:
          - name: ihelp-files
            persistentVolumeClaim:
              claimName: ihelp-app-avax-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ihelp-app-avax-pv
  namespace: ihelp-app-avax
  labels:
    dir: ihelp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /core/ihelp
    server: 208.59.77.70
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ihelp-app-avax-pvc
  namespace: ihelp-app-avax
spec:
  selector:
    matchLabels:
      dir: ihelp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ihelp-app-avax
