apiVersion: v1
kind: Pod
metadata:
  name: collect-run
  namespace: ihelp-app-avax
spec:
  restartPolicy: Never
  containers:
  - name: collect-run
    image: node:12
    volumeMounts:
    - mountPath: /core/ihelp
      name: ihelp-files
    workingDir: /core/ihelp/ihelp-dev-avax/packages/hardhat/scripts
    command: ["./runCollect.sh"]
  volumes:
  - name: ihelp-files
    persistentVolumeClaim:
      claimName: ihelp-app-avax-pvc
