FROM postgres:14

RUN apt-get update
RUN apt-get install curl build-essential nginx -y

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

RUN . "/root/.nvm/nvm.sh"

CMD [ "/bin/bash" ]